### ISSUE TITLE
npm init docs?

### ISSUE THREAD

**Issue by reywright** [jxnblk/mdx-docs#20]
The installation instructions are a bit vague. all `npm init docs` does for me is generate a package.json file.

**Comment by jxnblk** [comment]
Are you using windows by chance? There's a bug where the install won't work on windows machines currently, and I haven't had any time to investigate it

**Comment by reywright** [comment]
no, Mac.

Essentially, I don't use NEXT, but I'd really like to use this "styleguide" functionality in my own application. I have a bunch of reusable components built, and I want to get something similar to your Priceline One setup. I can clone your Priceline One setup and try to reverse engineer it, but wondering if you have a guide to more simply set it up, assuming I'm starting from scratch.

I'm also wondering: it seems you've opted for a more separate setup (going by your priceline setup) where you're opting for separating the examples from the actual code. Is there a way to make this work where the examples live with the code? What is your take on the fact the examples are separated from the code itself? Would that encourage staleness, or do you not think that is an issue?

**Comment by jxnblk** [comment]
Hmm, it *should* be copying and installing this folder: https://github.com/jxnblk/mdx-docs/tree/master/templates/next – so this sounds like a bug

> Essentially, I don't use NEXT, but I'd really like to use this "styleguide" functionality in my own application

Sounds like this is inline with some of the goals of this project. Ideally the mdx-docs components would be build/app agnostic so that they'd work in CRA, Gatsby, or any other React app. The current issue I'm trying to figure out is related to routing – i.e. how to decouple the navigation and links from the app's router. Currently there's a lot of coupling with Next.js, but those parts should be configurable. You might want to take a look around this repo, which is where I'm exploring how to make the "docs" components more generalized and not tied to any one implementation or CSS-in-JS library

**Comment by reywright** [comment]
`npm init docs` just helps you creates a package.json file by default. I'm still not totally sure what you're referring to.

**Comment by jxnblk** [comment]
Oh, sounds like you might be using an old version of npm that doesn’t support `create-<scope>` with init. See the examples here: https://docs.npmjs.com/cli/init#examples

For your other question, Next.js requires a specific directory structure, you might wanna look into docz if you wanna mix files within your source code

**Comment by zackkrida** [comment]
On a related note to `npm init docs`, upon running that command i had to install several packages referenced in the example app but not included in package.json by default:

`npm i mdx-docs remark-autolink-headings remark-emoji remark-images remark-slug remark-unwrap-images`
`npm i -D @mdx-js/loader`

**Comment by atav1k** [comment]
Thanks @zackkrida, that solved it for me

**Comment by nicholaai** [comment]
I'm also trying to use mdx-docs in the same way `priceline-design-system` does. though, when i run `npm init docs`, git doesn't track the contents of `/docs` and warns

```
warning: adding embedded git repository: docs
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint: 	git submodule add <url> docs
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint: 	git rm --cached docs
hint:
hint: See "git help submodule" for more information.
```

if run `git status` you get

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docs/

nothing added to commit but untracked files present (use "git add" to track)
```

if i clone `priceline`, delete the `/docs` folder, and run `npm init docs`, git properly tracks the files in the folder. `git status` shows all the deleted / modified files and then shows unchecked as

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docs/package-lock.json
	docs/pages/components/
	docs/pages/getting-started.md
```


is there something i'm missing here? did you run into this same issue, @reywright? thanks in advance, @jxnblk

**Comment by spences10** [comment]
Hi, I'm wondering why this issue was closed @jxnblk? 

The getting started isn't any clearer, can you clarify is this to be set up inside an existing project à la Docz or can you set up a new standalone project?
