### ISSUE TITLE
Local images

### ISSUE THREAD

**Issue by atav1k** [jxnblk/mdx-docs#30]
How would I use local images? I know it supports absolute URLs. Right now I imagine I'd need to make an image component.

**Comment by johno** [comment]
The best way to work with images in x0 is to use a CDN since we try to avoid dealing with them in the bundle. We currently have an undocumented cli to publish to our imgix fronted bucket you can use with:

```
npx @compositor/img ./path/to/image.png
```

Then you can use the returned url in place of the local image.

**Comment by atav1k** [comment]
Thanks @johno, that works. Haven't decided whether to go with mdx-go or -docs yet, might just draft in -go and build up the hosted site & port once images etc are finalized.

Also, loving these tools y'all.
